### ISSUE TITLE
FSharp.Core incompatibility

### ISSUE THREAD

**Issue by brianberns** [yazeedobaid/openai-fsharp#2]
Using the latest version of Visual Studio:

```
Detected package version outside of dependency constraint: OpenAI.Client 0.1.0 requires FSharp.Core (= 7.0.0) but version FSharp.Core 7.0.200 was resolved.
```

Is there a reason that FSharp.Core versions > 7.0.0 aren't accepted?

**Comment by yazeedobaid** [comment]
I have released a new version with a relaxed dependency constraint on `FSharp.Core`. Please use newer version `0.1.1`

**Comment by yazeedobaid** [comment]
I'll close the issue now, please feel free to re-open if issue still exists
